[
  Quantix(
    id: "69fa1c933ad81a99cecc92b2",
    fact: "Wood Frogs Survive Being Frozen Solid During The Arctic Winter",
    shortDescription: "Wood frogs stop their hearts and freeze completely solid to survive harsh winters in the frozen north woods.",
    longDescription: "Deep in the Arctic, the wood frog survives conditions that would kill almost any other vertebrate. As temperatures plummet, these amphibians allow their own blood and tissues to freeze, effectively stopping their heart and breathing for weeks at a time. To prevent cellular damage from ice crystals, they flood their bloodstream with a natural antifreeze made of glucose and urea. This high concentration of sugar acts as a biological cryoprotectant, keeping their vital organs intact while the rest of their body turns into a literal frog-shaped popsicle. Once spring arrives, the ice melts, their heart restarts, and they simply hop away, having successfully cheated death through complex chemistry.",
    quantixCategory: QuantixCategory.ANIMALS,
    createdAt: DateTime.parse("2026-05-05T16:36:35.078Z"),
    quizQuestion: "How do wood frogs survive winter?",
    quizOptions: ["Freezing", "Hibernating", "Migrating", "Burrowing"],
    quizAnswer: "Freezing",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69fa1c933ad81a99cecc92b2.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69fa1c933ad81a99cecc92b2-1779124804441.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69fa1c933ad81a99cecc92b2-1778502264334.mp3",
  ),
  Quantix(
    id: "69fa1cc03ad81a99cecc92b3",
    fact: "Giant Underground Rivers Flow Beneath The Amazon Rainforest Canopy Floor",
    shortDescription: "Immense subterranean rivers transport more water than the Amazon River itself through porous rock deep underground.",
    longDescription: "Deep beneath the lush surface of the Amazon rainforest lies a hidden hydrological giant known as the Hamza River. Stretching four thousand kilometers from the Andes to the Atlantic, this massive aquifer flows through porous sedimentary rock at a sluggish pace of mere millimeters per year. Unlike the surface river that rushes toward the ocean, this subterranean behemoth remains trapped in darkness, moving vertically through the crust before turning horizontal. Discovered by researchers analyzing heat data from retired oil wells, this geological anomaly proves that the true scale of the Amazon Basin's water cycle extends far deeper into the Earth's crust than any satellite or explorer could ever observe from the surface.",
    quantixCategory: QuantixCategory.EARTH_SCIENCE,
    createdAt: DateTime.parse("2026-05-05T16:37:20.526Z"),
    quizQuestion: "What lies beneath the Amazon rainforest?",
    quizOptions: ["Aquifer", "Magma", "Cave", "Oil"],
    quizAnswer: "Aquifer",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69fa1cc03ad81a99cecc92b3.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69fa1cc03ad81a99cecc92b3-1779168428388.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69fa1cc03ad81a99cecc92b3-1778502624770.mp3",
  ),
  Quantix(
    id: "69fa304adabff1126193b21c",
    fact: "Slime Molds Solve Complex Mazes Without Having Any Brains At All",
    shortDescription: "Single-celled slime molds successfully navigate intricate labyrinths to locate food sources using only chemical signaling and rhythmic pulses.",
    longDescription: "Physarum polycephalum, a single-celled organism known as a slime mold, exhibits intelligence that defies conventional biological logic. Despite lacking neurons, synapses, or a centralized brain, this golden, amoeba-like organism can navigate complex mazes to find the shortest path to oat flakes. It functions as a decentralized network, utilizing rhythmic contractions to distribute nutrients and information across its entire body simultaneously. When placed in a grid mirroring the layout of Tokyo's railway system, the slime mold spontaneously reconstructed an efficient network nearly identical to the human-designed transit lines. This remarkable behavior challenges our understanding of cognition, proving that complex decision-making and efficient problem-solving do not strictly require a nervous system to function effectively.",
    quantixCategory: QuantixCategory.ANIMALS,
    createdAt: DateTime.parse("2026-05-05T18:00:42.724Z"),
    quizQuestion: "Which organism navigates mazes without brains?",
    quizOptions: ["Slime Mold", "Coral", "Fungi", "Algae"],
    quizAnswer: "Slime Mold",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69fa304adabff1126193b21c.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69fa304adabff1126193b21c-1779168903087.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69fa304adabff1126193b21c-1778502683223.mp3",
  ),
  Quantix(
    id: "69fa3161dabff1126193b21d",
    fact: "Ancient Frozen Methane Bubbles Create Deadly Traps Under Arctic Lakes",
    shortDescription: "Trapped methane gas beneath thick Arctic lake ice creates explosive pockets that threaten unsuspecting frozen winter landscapes daily.",
    longDescription: "Deep beneath the frozen surface of Arctic lakes, microbial life breaks down organic matter, releasing vast quantities of methane gas. As winter temperatures plummet, this gas becomes trapped by the rapidly thickening ice, forming distinct, suspended white orbs that look like frozen bubbles captured in time. These structures are not merely aesthetic; they are high-pressure reservoirs of volatile greenhouse gas. When the ice cracks or melts, these pockets can release concentrated bursts of methane into the atmosphere. Scientists study these formations to better understand how warming permafrost alters global climate cycles, turning these beautiful, jagged winter displays into critical indicators of the hidden chemical exchanges occurring beneath our feet in the remote, shivering north.",
    quantixCategory: QuantixCategory.EARTH_SCIENCE,
    createdAt: DateTime.parse("2026-05-05T18:05:21.583Z"),
    quizQuestion: "Which gas is trapped under lake ice?",
    quizOptions: ["Methane", "Oxygen", "Helium", "Nitrogen"],
    quizAnswer: "Methane",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69fa3161dabff1126193b21d.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69fa3161dabff1126193b21d-1779169382891.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69fa3161dabff1126193b21d-1778504016318.mp3",
  ),
  Quantix(
    id: "69fad54a11a2b83193e19e54",
    fact: "Sea otters hold hands while sleeping to prevent drifting apart.",
    shortDescription: "Sea otters tether themselves together with kelp or by grasping paws to maintain group cohesion during deep sleep.",
    longDescription: "In the chilly waters of the Pacific, sea otters exhibit a heartwarming survival behavior known as rafting. To avoid drifting away from their social group or getting swept out to sea by strong ocean currents while they slumber, they often entangle themselves in strands of giant kelp. Even more fascinating is their habit of holding hands with their mates or pups. This physical connection acts as a biological anchor, ensuring the family unit remains intact throughout the night. This social bonding not only provides safety against the tides but also reinforces the strong maternal and communal ties essential for the survival of the species in their rugged, aquatic environment.",
    quantixCategory: QuantixCategory.ANIMALS,
    createdAt: DateTime.parse("2026-05-06T05:44:42.813Z"),
    quizQuestion: "Why do sea otters hold hands?",
    quizOptions: ["Social play", "Prevent drifting", "Share warmth", "Identify mates"],
    quizAnswer: "Prevent drifting",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69fad54a11a2b83193e19e54.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69fad54a11a2b83193e19e54-1779169862808.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69fad54a11a2b83193e19e54-1778504131240.mp3",
  ),
  Quantix(
    id: "69fad5c211a2b83193e19e55",
    fact: "Deep ocean microbes eat pure rock to survive without sunlight.",
    shortDescription: "Microbes living miles beneath the seafloor extract energy from volcanic minerals rather than relying on photosynthesis or organic decay.",
    longDescription: "Deep beneath the seafloor, in the crushing darkness of the Earth's crust, a mysterious biological world thrives. Scientists have discovered thriving communities of microbes living in basalt rock layers miles below the ocean floor. Unlike surface life that depends on the sun, these organisms practice lithotrophy, essentially eating the stone itself. They break down iron and sulfur compounds found within volcanic rock to fuel their metabolism. This discovery fundamentally shifts our understanding of life's resilience, suggesting that the interior of our planet is not a sterile void, but a massive, hidden habitat. It raises tantalizing possibilities that similar life forms might exist within the rocky crusts of other moons and planets across our solar system.",
    quantixCategory: QuantixCategory.EARTH_SCIENCE,
    createdAt: DateTime.parse("2026-05-06T05:46:42.124Z"),
    quizQuestion: "How do deep ocean microbes obtain energy?",
    quizOptions: ["Sunlight absorption", "Eating rock", "Consuming oxygen", "Thermal radiation"],
    quizAnswer: "Eating rock",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69fad5c211a2b83193e19e55.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69fad5c211a2b83193e19e55-1779170287693.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69fad5c211a2b83193e19e55-1778505518786.mp3",
  ),
  Quantix(
    id: "69fad63b11a2b83193e19e56",
    fact: "Neutron stars are so dense a teaspoon weighs one billion tons.",
    shortDescription: "A teaspoon of neutron star material weighs as much as the entire human population of Earth combined today.",
    longDescription: "When a massive star exhausts its nuclear fuel, it undergoes a cataclysmic collapse, crushing its core into a sphere only twenty kilometers wide. This remnant, known as a neutron star, packs the mass of our Sun into a volume no larger than a city. The resulting density is so extreme that protons and electrons are fused into neutrons, creating a superfluid core. If you were to scoop up a mere teaspoon of this exotic matter, the gravitational force would be so intense that the substance would instantly plummet through the Earth's crust, tearing through the planet to settle at its core, leaving a trail of destruction in its wake.",
    quantixCategory: QuantixCategory.SPACE,
    createdAt: DateTime.parse("2026-05-06T05:48:43.033Z"),
    quizQuestion: "How much does a neutron star weigh?",
    quizOptions: ["One billion tons", "Ten thousand tons", "Five million tons", "One hundred tons"],
    quizAnswer: "One billion tons",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69fad63b11a2b83193e19e56.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69fad63b11a2b83193e19e56-1779170702758.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69fad63b11a2b83193e19e56-1778506116580.mp3",
  ),
  Quantix(
    id: "69fad6ad11a2b83193e19e57",
    fact: "Time moves slower for objects traveling at very high speeds.",
    shortDescription: "Time dilation occurs because the speed of light remains constant for all observers regardless of their relative motion.",
    longDescription: "According to Einstein’s theory of special relativity, time is not an absolute constant but a relative dimension linked to space. As an object accelerates toward the speed of light, the passage of time for that object slows down relative to an observer at rest. This phenomenon, known as time dilation, is not merely a theoretical prediction; it has been empirically verified using atomic clocks on high-speed jets and orbiting satellites. If you were to travel on a spaceship near the speed of light, you would return to Earth to find that decades had passed for everyone else while only a few years had elapsed for you. This fundamental property of our universe defies our everyday intuition.",
    quantixCategory: QuantixCategory.PHYSICS,
    createdAt: DateTime.parse("2026-05-06T05:50:37.951Z"),
    quizQuestion: "What happens to time at high speeds?",
    quizOptions: ["Time speeds up", "Time slows down", "Time remains constant", "Time stops completely"],
    quizAnswer: "Time slows down",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69fad6ad11a2b83193e19e57.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69fad6ad11a2b83193e19e57-1779171122792.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69fad6ad11a2b83193e19e57-1778510323227.mp3",
  ),
  Quantix(
    id: "69fad71411a2b83193e19e58",
    fact: "Gallium metal melts instantly when held in a human hand.",
    shortDescription: "Gallium is a soft metal that transforms from a solid to a liquid at just 29.7 degrees Celsius.",
    longDescription: "Gallium is a fascinating metallic element that defies the common expectation that all metals are hard and rigid at room temperature. With a melting point of only 29.7 degrees Celsius, just slightly below human body temperature, a solid chunk of gallium will begin to liquefy the moment you hold it in your palm. This process is not a chemical reaction but a physical phase change triggered by your body's thermal energy. When it cools, it reverts to a beautiful, crystalline solid. This unique property makes gallium a popular element in science demonstrations, as it provides a tangible, real-world look at how atomic lattices respond to heat, making the invisible world of thermodynamics visible to the naked eye.",
    quantixCategory: QuantixCategory.CHEMISTRY,
    createdAt: DateTime.parse("2026-05-06T05:52:20.378Z"),
    quizQuestion: "At what temperature does gallium melt?",
    quizOptions: ["29.7 Celsius", "50.0 Celsius", "10.5 Celsius", "98.6 Celsius"],
    quizAnswer: "29.7 Celsius",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69fad71411a2b83193e19e58.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69fad71411a2b83193e19e58-1779171543476.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69fad71411a2b83193e19e58-1778510389989.mp3",
  ),
  Quantix(
    id: "69fad79811a2b83193e19e59",
    fact: "Your brain can create false memories that feel completely real.",
    shortDescription: "The human mind reconstructs experiences every time they are recalled, often injecting fiction into historical events.",
    longDescription: "Memory is not a static video recording stored in a library. Instead, the brain treats memory as a dynamic reconstruction project. Every time you retrieve a past experience, the hippocampus and prefrontal cortex assemble fragments of information, often filling in gaps with logical inferences or suggestions from others. Because the brain uses the same neural pathways for imagining the future and recalling the past, these generated details can become indistinguishable from actual sensory input. This phenomenon, known as the misinformation effect, proves that our personal history is a fluid narrative subject to constant revision, meaning that what we perceive as 'truth' can be subtly rewritten by the very act of thinking about it.",
    quantixCategory: QuantixCategory.BRAIN_MIND,
    createdAt: DateTime.parse("2026-05-06T05:54:32.248Z"),
    quizQuestion: "How does the brain process stored memories?",
    quizOptions: ["Static recording", "Dynamic reconstruction", "Video playback", "Constant deletion"],
    quizAnswer: "Dynamic reconstruction",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69fad79811a2b83193e19e59-1778510896605.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69fad79811a2b83193e19e59-1779183963271.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69fad79811a2b83193e19e59-1778511116891.mp3",
  ),
  Quantix(
    id: "69fad81c11a2b83193e19e5a",
    fact: "Stomach acid can dissolve metal blades without damaging the organ.",
    shortDescription: "Stomach acid is so powerful it can dissolve razor blades while the lining protects the organ itself.",
    longDescription: "The human stomach contains hydrochloric acid with a pH level between one and three. This extreme acidity is essential for breaking down complex proteins and neutralizing harmful bacteria ingested with food. To prevent the stomach from digesting itself, the organ is coated in a thick layer of protective mucus and rapidly regenerates its own lining cells every few days. This robust defense mechanism is so efficient that the stomach can withstand corrosive substances capable of dissolving various metals. While the stomach is incredibly resilient, it requires this specific chemical environment to initiate digestion, proving that our internal physiological processes involve intense, controlled chemical reactions that maintain our survival every single day.",
    quantixCategory: QuantixCategory.HUMAN_BODY,
    createdAt: DateTime.parse("2026-05-06T05:56:44.544Z"),
    quizQuestion: "What does the human stomach contain?",
    quizOptions: ["Sulfuric acid", "Hydrochloric acid", "Acetic acid", "Nitric acid"],
    quizAnswer: "Hydrochloric acid",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69fad81c11a2b83193e19e5a.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69fad81c11a2b83193e19e5a-1779184622991.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69fad81c11a2b83193e19e5a-1778686545552.mp3",
  ),
  Quantix(
    id: "69fad87b11a2b83193e19e5b",
    fact: "The first computer programmer in history was a Victorian woman.",
    shortDescription: "Ada Lovelace wrote the world's first machine algorithm in 1843 for Charles Babbage's proposed mechanical general-purpose computer, the Analytical Engine.",
    longDescription: "In 1843, Ada Lovelace, the daughter of the poet Lord Byron, published a set of notes on the Analytical Engine, a theoretical machine designed by Charles Babbage. While others saw the device merely as a calculator for numbers, Lovelace realized its true potential went far beyond simple arithmetic. She authored a sophisticated algorithm intended for the machine to calculate Bernoulli numbers, effectively creating the world’s first computer program. Lovelace envisioned that computers could manipulate symbols and potentially compose music or create graphics, anticipating the digital age by over a century. Her profound insight into the logical capabilities of machines laid the fundamental groundwork for modern computer science, forever changing how we perceive human-machine collaboration.",
    quantixCategory: QuantixCategory.SCIENCE_HISTORY,
    createdAt: DateTime.parse("2026-05-06T05:58:19.675Z"),
    quizQuestion: "Who wrote the first computer program?",
    quizOptions: ["Ada Lovelace", "Charles Babbage", "Alan Turing", "Grace Hopper"],
    quizAnswer: "Ada Lovelace",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69fad87b11a2b83193e19e5b.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69fad87b11a2b83193e19e5b-1779185404162.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69fad87b11a2b83193e19e5b-1778686605948.mp3",
  ),
  Quantix(
    id: "69fad8f311a2b83193e19e5c",
    fact: "Soft robotic grippers can handle delicate objects using pressurized air channels.",
    shortDescription: "Soft robotic grippers use pneumatic inflation to mimic human fingers, allowing them to grasp fragile items without any damage.",
    longDescription: "Traditional industrial robots rely on rigid metal pincers that often crush fragile goods like fruit or delicate glassware. To solve this, engineers developed soft robotics made from flexible silicone elastomers. These grippers feature internal air chambers that expand when pressurized, causing the robotic fingers to curl gently around an object. By precisely controlling the air pressure, these robots can mimic the dexterity and sensitivity of a human hand. This technology is revolutionizing logistics and food processing, enabling automated systems to sort ripe strawberries or handle electronics without leaving a single scratch. It represents a fundamental shift from brute-force machinery to biomimetic systems designed to interact safely within human environments and delicate industrial workflows.",
    quantixCategory: QuantixCategory.TECHNOLOGY,
    createdAt: DateTime.parse("2026-05-06T06:00:19.629Z"),
    quizQuestion: "How do soft robotic grippers work?",
    quizOptions: ["Pressurized air", "Magnetic force", "Hydraulic fluid", "Vacuum suction"],
    quizAnswer: "Pressurized air",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69fad8f311a2b83193e19e5c.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69fad8f311a2b83193e19e5c-1779187863871.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69fad8f311a2b83193e19e5c-1778686676673.mp3",
  ),
  Quantix(
    id: "69fad97011a2b83193e19e5d",
    fact: "Male seahorses carry and give birth to their own offspring.",
    shortDescription: "Male seahorses possess a specialized brood pouch where they incubate eggs and deliver fully developed baby seahorses.",
    longDescription: "In the underwater world of Syngnathidae, the traditional roles of reproduction are dramatically flipped. During mating, the female deposits her eggs directly into the male’s ventral brood pouch. Once inside, the male fertilizes the eggs and provides a highly controlled environment, regulating salinity and nutrients as they develop. Over the course of several weeks, the male nurtures these embryos until they are ready to enter the ocean. When the time is right, he undergoes rhythmic muscular contractions to expel dozens of tiny, independent fry into the water. This unique evolutionary adaptation allows the species to maximize reproductive efficiency, freeing the female to begin producing a new batch of eggs almost immediately.",
    quantixCategory: QuantixCategory.ANIMALS,
    createdAt: DateTime.parse("2026-05-06T06:02:24.410Z"),
    quizQuestion: "Which seahorse gender carries the eggs?",
    quizOptions: ["Only females", "Only males", "Both parents", "Neither parent"],
    quizAnswer: "Only males",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69fad97011a2b83193e19e5d.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69fad97011a2b83193e19e5d-1779188642807.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69fad97011a2b83193e19e5d-1778686801530.mp3",
  ),
  Quantix(
    id: "69fada6811a2b83193e19e5f",
    fact: "The diamond planet 55 Cancri e is twice Earth's size.",
    shortDescription: "This super-Earth is composed largely of carbon in the form of diamond and graphite due to extreme pressure.",
    longDescription: "Located about 40 light-years away, the exoplanet 55 Cancri e orbits its host star so closely that a single year lasts only 18 hours. This proximity creates surface temperatures exceeding 2,000 degrees Celsius, essentially melting the planet's surface. Scientific analysis suggests the interior is rich in diamond and graphite, as the carbon-to-oxygen ratio is significantly higher than that of our solar system. Unlike the silicate-rich composition of Earth, this world represents a bizarre class of carbon-heavy planets. The intense gravitational pressure and heat rearrange carbon atoms into crystalline lattices, suggesting that a significant portion of the planet's mass exists as massive, exotic diamond layers beneath a volatile, molten surface.",
    quantixCategory: QuantixCategory.SPACE,
    createdAt: DateTime.parse("2026-05-06T06:06:32.932Z"),
    quizQuestion: "What is the primary composition of 55 Cancri e?",
    quizOptions: ["Solid diamond", "Liquid water", "Frozen methane", "Molten iron"],
    quizAnswer: "Solid diamond",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69fada6811a2b83193e19e5f.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69fada6811a2b83193e19e5f-1779208633310.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69fada6811a2b83193e19e5f-1778687030552.mp3",
  ),
  Quantix(
    id: "69faf80ae62a4a9f68629338",
    fact: "Fluorine is the most reactive element in the entire periodic table.",
    shortDescription: "Fluorine atoms aggressively snatch electrons from almost any other substance, making them chemically violent and highly dangerous.",
    longDescription: "Fluorine is the chemical equivalent of an impatient thief. As the most electronegative element, its atoms possess an insatiable hunger for electrons, pulling them away from virtually any other material they encounter. This extreme reactivity means fluorine can set fire to materials that are typically flame-retardant, including asbestos and even water. In industrial applications, scientists must store fluorine in specialized nickel containers because the metal forms a protective fluoride layer that prevents further damage. Handling this element requires immense caution, as its aggressive nature causes it to vaporize organic tissue upon contact. It is a fundamental building block of modern chemistry, yet it remains one of the most volatile substances ever discovered in nature.",
    quantixCategory: QuantixCategory.CHEMISTRY,
    createdAt: DateTime.parse("2026-05-06T08:12:58.862Z"),
    quizQuestion: "Which element is the most reactive?",
    quizOptions: ["Helium", "Gold", "Fluorine", "Iron"],
    quizAnswer: "Fluorine",
    imageUrl: "https://cdn.adquizzerltd.com/quantix/facts/69faf80ae62a4a9f68629338.webp",
    videoUrl: "https://cdn.adquizzerltd.com/quantix/video/69faf80ae62a4a9f68629338-1779210546145.mp4",
    audioUrl: "https://cdn.adquizzerltd.com/quantix/audio/69faf80ae62a4a9f68629338-1779168515164.mp3",
  )
]
